###############################################################
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

---
version: 2
updates:

  # Divide into two nuget scans due to timeout of Github action run after 55 minutes without split

  # NuGet
  -
    package-ecosystem: "nuget"
    directory: "/src/"
    labels:
      - "dependabot"
      - "dependencies"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    allow:
      - dependency-name: "Microsoft.*"
    groups:
      default:
        patterns:
          - "*"

  # NuGet
  -
    package-ecosystem: "nuget"
    directory: "/src/"
    # Makes it possible to have another nuget configuration for the same directory.
    # https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    target-branch: main
    labels:
      - "dependabot"
      - "dependencies"
    schedule:
      interval: "weekly"
    # Ignore xunit* because scan fails when included
    ignore:
      - dependency-name: "Microsoft.*"
      - dependency-name: "xunit*"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      default:
        patterns:
          - "*"

  # Github Actions
  -
    package-ecosystem: "github-actions"
    directory: /
    labels:
      - "dependabot"
      - "github-actions"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        dependency-type: "production"

  # Docker
  -
    package-ecosystem: "docker"
    directory: ./docker/
    labels:
      - "dependabot"
      - "docker"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      dependencies:
        dependency-type: "production"
