###############################################################
# Copyright (c) 2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS publish
ARG TARGETARCH
COPY LICENSE NOTICE.md DEPENDENCIES /
COPY src/maintenance/Maintenance.App/ src/maintenance/Maintenance.App/
COPY src/portalbackend/PortalBackend.DBAccess/ src/portalbackend/PortalBackend.DBAccess/
COPY src/portalbackend/PortalBackend.PortalEntities/ src/portalbackend/PortalBackend.PortalEntities/
COPY src/externalsystems/Clearinghouse.Library/ src/externalsystems/Clearinghouse.Library/
COPY src/externalsystems/Custodian.Library/ src/externalsystems/Custodian.Library/
COPY src/framework/ src/framework/
COPY src/processes/Processes.ProcessIdentity/ src/processes/Processes.ProcessIdentity/
COPY src/processes/ApplicationChecklist.Library/ src/processes/ApplicationChecklist.Library/
RUN dotnet restore "src/maintenance/Maintenance.App/Maintenance.App.csproj"
WORKDIR /src/maintenance/Maintenance.App
RUN dotnet publish "Maintenance.App.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:9.0-alpine
ENV COMPlus_EnableDiagnostics=0
WORKDIR /app
COPY --from=publish /app/publish .
RUN chown -R 1000:3000 /app
USER 1000:3000
ENTRYPOINT ["dotnet", "Org.Eclipse.TractusX.Portal.Backend.Maintenance.App.dll"]
