###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

FROM mcr.microsoft.com/dotnet/runtime:7.0-alpine AS base

FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine-amd64 AS publish
WORKDIR /
COPY LICENSE NOTICE.md DEPENDENCIES /
COPY /src/keycloak/Keycloak.ErrorHandling /src/keycloak/Keycloak.ErrorHandling
COPY /src/keycloak/Keycloak.Factory /src/keycloak/Keycloak.Factory
COPY /src/keycloak/Keycloak.Library /src/keycloak/Keycloak.Library
COPY /src/keycloak/Keycloak.Seeding /src/keycloak/Keycloak.Seeding
WORKDIR /src/keycloak/Keycloak.Seeding
RUN dotnet publish "Keycloak.Seeding.csproj" -c Release -o /app/publish

FROM base AS final
ENV COMPlus_EnableDiagnostics=0
WORKDIR /app
COPY --from=publish /app/publish .
RUN chown -R 1000:3000 /app
USER 1000:3000
ENTRYPOINT ["dotnet", "Org.Eclipse.TractusX.Portal.Backend.Keycloak.Seeding.dll"]
