FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine AS base

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /
COPY src/checklist/Checklist.Worker/ src/checklist/Checklist.Worker/
COPY src/checklist/Checklist.Library/ src/checklist/Checklist.Library/
COPY src/portalbackend/PortalBackend.PortalEntities/ src/portalbackend/PortalBackend.PortalEntities/
RUN dotnet restore "src/checklist/Checklist.Worker/Checklist.Worker.csproj"
WORKDIR /src/checklist/Checklist.Worker
RUN dotnet build "Checklist.Worker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Checklist.Worker.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN chown -R 1000:3000 /app
USER 1000:3000
ENTRYPOINT ["dotnet", "Org.Eclipse.TractusX.Portal.Backend.Checklist.Worker.dll"]
