#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /
RUN dotnet tool install dotnet-ef -g
ENV PATH $PATH:/root/.dotnet/tools
COPY /src/portalbackend /src/portalbackend
WORKDIR /src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations
RUN dotnet-ef migrations bundle -r linux-x64

FROM base AS final
WORKDIR /migrations
COPY --from=build /src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/efbundle .
ENTRYPOINT ["./efbundle"]