FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR src/ src/
COPY ["src/maintenance/CatenaX.NetworkServices.Maintenance.App/CatenaX.NetworkServices.Maintenance.App.csproj", "CatenaX.NetworkServices.Maintenance.App/"]
RUN dotnet restore "maintenance/CatenaX.NetworkServices.Maintenance.App/CatenaX.NetworkServices.Maintenance.App.csproj"
COPY . .
WORKDIR "/src/maintenance/CatenaX.NetworkServices.Maintenance.App"
RUN dotnet build "CatenaX.NetworkServices.Maintenance.App.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CatenaX.NetworkServices.Maintenance.App.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CatenaX.NetworkServices.Maintenance.App.dll"]
