###############################################################
# Copyright (c) 2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS publish
ARG TARGETARCH
COPY LICENSE NOTICE.md DEPENDENCIES /
COPY /src/provisioning /src/provisioning
COPY /src/framework/Framework.ErrorHandling /src/framework/Framework.ErrorHandling
COPY /src/framework/Framework.Seeding /src/framework/Framework.Seeding
COPY /src/framework/Framework.Models /src/framework/Framework.Models
COPY /src/framework/Framework.Linq /src/framework/Framework.Linq
COPY /src/framework/Framework.Logging /src/framework/Framework.Logging
WORKDIR /src/provisioning/Provisioning.Migrations
RUN dotnet publish "Provisioning.Migrations.csproj" -c Release -o /migrations/publish

FROM mcr.microsoft.com/dotnet/runtime:8.0-alpine
ENV COMPlus_EnableDiagnostics=0
WORKDIR /migrations
COPY --from=publish /migrations/publish .
RUN chown -R 1000:3000 /migrations
USER 1000:3000
ENTRYPOINT ["dotnet", "Org.Eclipse.TractusX.Portal.Backend.Provisioning.Migrations.dll"]
