FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /
COPY src/ src/
WORKDIR /src/notifications/Notifications.Service
RUN dotnet build "Notifications.Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Notifications.Service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS http://+:8080
EXPOSE 8080
RUN chown -R 1000:3000 /app
USER 1000:3000
ENTRYPOINT ["dotnet", "Org.Eclipse.TractusX.Portal.Backend.Notification.Service.dll"]
