FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine AS base

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /
COPY src/maintenance/CatenaX.NetworkServices.Maintenance.App/ src/maintenance/CatenaX.NetworkServices.Maintenance.App/
COPY src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/ src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/
RUN dotnet restore "src/maintenance/CatenaX.NetworkServices.Maintenance.App/CatenaX.NetworkServices.Maintenance.App.csproj"
WORKDIR /src/maintenance/CatenaX.NetworkServices.Maintenance.App
RUN dotnet build "CatenaX.NetworkServices.Maintenance.App.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CatenaX.NetworkServices.Maintenance.App.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS http://+:8080
EXPOSE 8080
RUN chown -R 1000:3000 /app
USER 1000:3000
ENTRYPOINT ["dotnet", "CatenaX.NetworkServices.Maintenance.App.dll"]
