name: Administration-Service

on:
  push:
    paths:
      # service path
      - 'src/administration/CatenaX.NetworkServices.Administration.Service/**'
      # workflow file
      - '.github/workflows/administration-service.yml'
      # dockerfile
      - 'docker/Dockerfile-administration-service'

    branches:
      - 'main'
      - 'feature/CPLP-1074_auto_image_update'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_administration-service
  COMMIT_SHA: ${{ github.sha }}
  IMAGE_BEGINN: 'administationtag: '
  IMAGE_FULL: 'administationtag: ${{ github.sha }}'

jobs:
  # build-and-push-image:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Extract Metadata (tags, labels) for Docker
  #       id: meta
  #       uses: docker/metadata-action@v3
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: docker/Dockerfile-administration-service
  #         pull: true
  #         push: true
  #         tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }}
  #         labels: ${{ steps.meta.outputs.labels }}

  update-image-tag:
    # needs: build-and-push-image
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout product-portal-cd repository
        uses: actions/checkout@v3
        with:
          repository: catenax-ng/product-portal-cd
          ref: feature/CPLP-1074_auto_image_update
          path: product-portal-cd/chart/portal-backend/values-dev.yaml

      - name: Modify image tag in product-portal-cd repo
        run: >
          sed -i 's/${{ env.IMAGE_BEGINN }}.*/${{ env.IMAGE_FULL }}/'
          product-portal-cd/chart/portal-backend/values-dev.yaml

      - name: Commit and push new image tag to product-portal-cd repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add product-portal-cd/chart/portal-backend/values-dev.yaml
          git commit -m "Add new image for administration service"
          git push
