name: Administration-Service

on:
  push:
    paths:
      # service path
      - 'src/administration/CatenaX.NetworkServices.Administration.Service/**'
      # workflow file
      - '.github/workflows/administration-service.yml'
      # dockerfile
      - 'docker/Dockerfile-administration-service'

    branches:
      - 'main'
      - 'feature/CPLP-1074_auto_image_update'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_administration-service
  COMMIT_SHA: ${{ github.sha }}
  IMAGE_BEGINN: 'administrationtag: '
  IMAGE_FULL: 'administrationtag: ${{ github.sha }}'

jobs:
  # build-and-push-image:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Extract Metadata (tags, labels) for Docker
  #       id: meta
  #       uses: docker/metadata-action@v3
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: docker/Dockerfile-administration-service
  #         pull: true
  #         push: true
  #         tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }}
  #         labels: ${{ steps.meta.outputs.labels }}

  # update-image-tag:
    # needs: build-and-push-image
    # runs-on: ubuntu-latest
    # permissions:
    #   contents: write

    # steps:
    #   - name: Checkout product-portal-cd repository
    #     uses: actions/checkout@v3
    #     with:
    #       persist-credentials: false
    #       fetch-depth: 0
    #       repository: catenax-ng/product-portal-cd
    #       ref: feature/CPLP-1074_auto_image_update

    #   - name: Modify image tag in values-dev.yaml
    #     run: |
    #       sed -i 's/${{ env.IMAGE_BEGINN }}.*/${{ env.IMAGE_FULL }}/' chart/portal-backend/values-dev.yaml

    #   - name: Commit and push updated values-dev.yaml to product-portal-cd repo
    #     run: |
    #       git config --global user.name "evegufy"
    #       git config --global user.email "evelyn.gurschler@bmw.de"
    #       git remote set-url origin git@github.com:evegufy/catenax-ng/product-portal-cd.git.git
    #       git add chart/portal-backend/values-dev.yaml
    #       git commit -m "Add new image for administration service"
    #       git push

  auth-and-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Get token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.ORG_PORTAL_DISPATCH_APPID }}
          application_private_key: ${{ secrets.ORG_PORTAL_DISPATCH_KEY }}
      
      #- name: trigger external action
      #  id: call_action
      #  env:
      #    API_TOKEN_GITHUB: ${{ steps.get_workflow_token.outputs.token }}
      #  uses: catenax-ng/playground-target/Demo@v1
      
      - name: Trigger workflow
        id: call_action
        env:
          TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          curl -v \
            --request POST \
            --url https://api.github.com/repos/catenax-ng/product-portal-cd/actions/workflows/administration-service-image-update.yml/dispatches \
            --header "authorization: Bearer $TOKEN" \
            --header "Accept: application/vnd.github.v3+json" \
            --data '{"ref":"feature/CPLP-1074_auto_image_update","inputs":{"updated-image":"test"}}' \
            --fail
