name: Portal-Migrations

on: 
  push:
    paths:
      # service and transitive paths
      - 'src/portalbackend/PortalBackend.Migrations/**'
      - 'src/portalbackend/PortalBackend.PortalEntities/**'
      # workflow file
      - '.github/workflows/portal-migrations.yml'
      # dockerfile
      - 'docker/Dockerfile-portal-migrations'

    branches:
      - 'main'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_portal-migrations
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-portal-migrations
          pull: true
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

  auth-and-dispatch:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
      - name: Get token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.ORG_PORTAL_DISPATCH_APPID }}
          application_private_key: ${{ secrets.ORG_PORTAL_DISPATCH_KEY }}

      - name: Trigger workflow
        id: call_action
        env:
          TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          curl -v \
            --request POST \
            --url https://api.github.com/repos/catenax-ng/tx-portal-cd/actions/workflows/portal-migrations-image-update.yml/dispatches \
            --header "authorization: Bearer $TOKEN" \
            --header "Accept: application/vnd.github.v3+json" \
            --data '{"ref":"helm-environments", "inputs": { "new-image":"${{ env.COMMIT_SHA }}" }}' \
            --fail
